### ISSUE TITLE
Not Support with Laravel 6.0.3

### ISSUE THREAD

**Issue by ahmedkamel1192** [laravel-notification-channels/onesignal#101]
i have got this error after run composer command 
"composer require laravel-notification-channels/onesignal"

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel-notification-channels/onesignal 1.2.0
    - Conclusion: remove laravel/framework v6.0.3
    - Installation request for laravel-notification-channels/onesignal ^1.2 -> satisfiable by laravel-notification-channels/onesignal[1.2.0, v1.2.0-rc.1].
    - Conclusion: don't install laravel/framework v6.0.3

**Comment by LKaemmerling** [comment]
As you can see in #98, we're working on it

**Comment by LKaemmerling** [comment]
v2.0.0 was just released which support Laravel 6.0

**Comment by ahmedkamel1192** [comment]
Good Job :+1:

**Comment by ahmedkamel1192** [comment]
> v2.0.0 was just released which support Laravel 6.0

can i use it by run this command 
composer require laravel-notification-channels/onesignal:v2.0.0 ???

**Comment by ahmedkamel1192** [comment]
> v2.0.0 was just released which support Laravel 6.0

is it take time to be shown in packagist ?

**Comment by LKaemmerling** [comment]
Really strange, i don't know why the sync does not work. We doesn't have control over this packagist account. @atymic can you look into this?

**Comment by atymic** [comment]
A bunch of other repos have the issue, we need @themsaid to fix it (he has the packagist account) :(

**Comment by atymic** [comment]
I'm just re-opening this while we wait for packagist to be fixed.

**Comment by r94ever** [comment]
Anyone know what happened with packagist?

**Comment by Lloople** [comment]
They changed the way external apps connect with GitHub API, so you have to give access again. But only the packagist account owner can do that so we need @themsaid in order to do that 😅

**Comment by r94ever** [comment]
> They changed the way external apps connect with GitHub API, so you have to give access again. But only the packagist account owner can do that so we need @themsaid in order to do that

And @themsaid hasn't done it yet, has him?

**Comment by atymic** [comment]
No, there a bunch of other repos with the issue as well
https://github.com/laravel-notification-channels/laravel-notification-channels.github.io/issues/25

**Comment by AshPowell** [comment]
> No, there a bunch of other repos with the issue as well
> [laravel-notification-channels/laravel-notification-channels.github.io#25](https://github.com/laravel-notification-channels/laravel-notification-channels.github.io/issues/25)

Is it also worth tagging Taylor in the todo you created to get this moved along? I'm guessing it's stopping a fair few apps from being updated that rely on these push notification channels :/

**Comment by atymic** [comment]
AFAIK taylor isn't involved in the notification channels (apart from working with @themsaid)

**Comment by AshPowell** [comment]
> AFAIK taylor isn't involved in the notification channels (apart from working with @themsaid)

I just thought maybe if we could get Taylor to drop him a PM that's all - I imagine there are a bunch waiting on these now - can't update to v6 because of this 😕

**Comment by atymic** [comment]
Github hooks should be syncing with packagist properly now. If there are any issues in the future ping me 😄
