### ISSUE TITLE
An unexpected TLS packet was received

### ISSUE THREAD

**Issue by mahavirvataliya** [laravel-notification-channels/onesignal#103]
Hello i get this error while sending Notification

gnutls_handshake() failed: An unexpected TLS packet was received. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 35: gnutls_handshake() failed: An unexpected TLS packet was received. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at /home/runcloud/webapps/cloint/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186)

**Comment by AshPowell** [comment]
I don't think this is an error regarding the package - seems more likely your server/environment.

> A problem occurred somewhere in the SSL/TLS handshake. You really want the error buffer and read the message there as it pinpoints the problem slightly more. Could be certificates (file formats, paths, permissions), passwords, and others.

**Comment by LKaemmerling** [comment]
Yep, this is not regarding this package. So i will close it :)
