### ISSUE TITLE
I got error while testing onesignal in Laravel app

### ISSUE THREAD

**Issue by tomavic** [laravel-notification-channels/onesignal#110]
When I try to test OneSignal to a fresh new laravel app, I get this message

```
cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to onesignal.com:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
I searched alot but nothing is clear about this issue

Please help

**Comment by LKaemmerling** [comment]
There is something wrong with your server/system as a connection to onesignal via SSL is not possible.

**Comment by tomavic** [comment]
@LKaemmerling what do you mean by something wron with server/system, and how can I detect it. I am really have no idea what's wrong

**Comment by LKaemmerling** [comment]
Have a look at https://stackoverflow.com/questions/13686398/ssl-read-failing-with-ssl-error-syscall-error . This is something on your system (or with your curl in general). I will close the issue.
