### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/onesignal#112]

**Comment by volkv** [comment]
Thats the only package (out of over 40) preventing us from upgrade to Laravel v7 and Nova v3. 
@LKaemmerling could you please commit that PR?

**Comment by LKaemmerling** [comment]
@volkv i'm just waiting for a review on this PR from @Lloople (or maybe @atymic ?)

**Comment by Lloople** [comment]
@LKaemmerling Done! 🤓

**Comment by LKaemmerling** [comment]
Releases as v2.1.0

**Comment by atymic** [comment]
Thanks guys!
