### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/onesignal#116]
Laravel 8 has been released today and we need to update this repo to support it.
See https://laravel.com/docs/8.x/upgrade & https://github.com/laravel-notification-channels/channels/issues/107

**Comment by ExpDev07** [comment]
I have oepend a PR here which should fix it: https://github.com/berkayk/laravel-onesignal/pull/135.

**Comment by pedro-santiago** [comment]
@ExpDev07 is this repo active? I've checked your PR (looking good, by the way), but they aren't quite very active, right?

**Comment by atymic** [comment]
If there's no movement in the next few days, you can always switch to a fork of that package
See the composer docs

**Comment by ExpDev07** [comment]
@atymic right, but I believe the owner of that repo is the same as this one XD

**Comment by atymic** [comment]
I don't have permissions on the other repo (I do on this one, as it's part of the notification channels)

**Comment by atymic** [comment]
Should be good now 👍
