### ISSUE TITLE
Laravel 8 support not working

### ISSUE THREAD

**Issue by ExpDev07** [laravel-notification-channels/onesignal#119]
Still not working. On `composer require laravel-notification-channels/onesignal` getting error: `Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].`

**Comment by j-jalving** [comment]
I'm getting `laravel-notification-channels/onesignal[v1.2.0-rc.1, ..., 1.2.0] require illuminate/notifications 5.* -> found illuminate/notifications[v5.3.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.`

**Comment by ExpDev07** [comment]
@j-jalving I got it working for laravel 8. Composer
```
"require": {
	"php": "^7.4",
	"expdev07/laravel-cashier-stripe-connect": "^1.0.2",
	"fideloper/proxy": "^4.2",
	"fruitcake/laravel-cors": "^1.0",
	"fzaninotto/faker": "^1.9.1",
	"guzzlehttp/guzzle": "^7.0.1",
	"intervention/image": "^2.5",
	"laravel-notification-channels/onesignal": "^2.2",
	"laravel/cashier": "^12.5",
	"laravel/framework": "^8.0",
	"laravel/tinker": "^2.0",
	"league/flysystem-aws-s3-v3": "~1.0",
	"mockery/mockery": "^1.3.1",
	"pusher/pusher-php-server": "~4.0",
	"spatie/laravel-medialibrary": "^9.0"
},
"require-dev": {
	"barryvdh/laravel-debugbar": "^3.5",
	"barryvdh/laravel-ide-helper": "^2.7",
	"facade/ignition": "^2.3.6",
	"nunomaduro/collision": "^5.0",
	"phpunit/phpunit": "^9.0"
}
```

**Comment by j-jalving** [comment]
I guess that works for PHP7.4, but not for PHP8

**Comment by ExpDev07** [comment]
I believe you might wanna open a separate issue for that @j-jalving
