### ISSUE TITLE
composer install not working

### ISSUE THREAD

**Issue by morganzysman** [laravel-notification-channels/onesignal#12]
Please,

Anyone could help me with this? Regards

 Problem 1
    - Installation request for laravel-notification-channels/onesignal ^1.0 -> satisfiable by laravel-notification-channels/onesignal[1.0.0].
    - laravel-notification-channels/onesignal 1.0.0 requires berkayk/onesignal-laravel ^0.9.3 -> satisfiable by berkayk/onesignal-laravel[v0.9.3, v0.9.4, v0.9.5].
    - berkayk/onesignal-laravel v0.9.3 requires symfony/psr-http-message-bridge ^0.2.0 -> satisfiable by symfony/psr-http-message-bridge[v0.2].
    - berkayk/onesignal-laravel v0.9.4 requires symfony/psr-http-message-bridge ^0.2.0 -> satisfiable by symfony/psr-http-message-bridge[v0.2].
    - berkayk/onesignal-laravel v0.9.5 requires symfony/psr-http-message-bridge ^0.2.0 -> satisfiable by symfony/psr-http-message-bridge[v0.2].
    - Conclusion: don't install symfony/psr-http-message-bridge v0.2

**Comment by ramisohail** [comment]
same issue here? any hints or fixes?

**Comment by hafael** [comment]
+1

I submitted a pull request to berkayk / laravel-onesignal by updating the symfony / psr-http-message-bridge to v1.x dependency.
I hope it does.

[https://github.com/berkayk/laravel-onesignal/pull/27](https://github.com/berkayk/laravel-onesignal/pull/27)
