### ISSUE TITLE
Enable or disable from .env

### ISSUE THREAD

**Issue by gguney** [laravel-notification-channels/onesignal#122]
I could not find any way to stop checking/sending one signal request via config etc. 

There maybe some situation to not send notifications and there is no way to do that.

Or do we ?

**Comment by LKaemmerling** [comment]
Why would you send a notification to OneSignal (from Laravel to this package) and then don't want to send it to OneSignals API? This doesn't makes sense in my mind. You need to stop it when Laravel gives it this package (so basically within your notification toOneSignal Method).

**Comment by gguney** [comment]
We have some notification system for automatically mapping user notification preferences to channels. I would like to be able to send or not send notifications from toOneSignalChannel. 

Even if I don't have one signal key or app id the one signal request happens and throws error.

**Comment by LKaemmerling** [comment]
You should implement the logic for this within your own code. This is not something we should add to our code as it might bring more "questions" than benefit for developers.

**Comment by gguney** [comment]
why not? Aren't we should be able to activate or deactivate it? What type of "questions" can it bring? I think developers should open or close this channel.

**Comment by gguney** [comment]
Since the so called "Collaborator" is not so helpful. I implemented method in my User model

`    
/**
     * @return array
     */
    public function routeNotificationForOneSignal()
    {
        return Config::get('onesignal.enabled') ? ['include_external_user_ids' => $this->id] : null;
    }
`

This way you can customize onesignal's enable or disable status from your config file.

**Comment by LKaemmerling** [comment]
You shouldn't send something to the channel when you don't want to send it to OneSignal :) That is basically completely valid, no need to be rude :) I said you exactly the thing you implemented, which is the "only" correct solution. Don't send something to the channel when you don't want to.
