### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by haoxi911** [laravel-notification-channels/onesignal#123]
Can someone advise what's the easiest way to make this library working on PHP 8? Thank you!

**Comment by myckhel** [comment]
composer.json
```json
"repositories": {
      "onesignal": {
        "type": "vcs",
        "url": "https://github.com/myckhel/onesignal"
      }
    }
```

Remove composer.lock
```bash
composer install
```

Temporary solution

**Comment by LKaemmerling** [comment]
Hey,

PHP 8 support was just merged into the master branch.
