### ISSUE TITLE
Publish new version to packagist

### ISSUE THREAD

**Issue by j-jalving** [laravel-notification-channels/onesignal#126]
Would you mind publishing a new version to Packagist for us running PHP8?

**Comment by lahivee** [comment]
Would really appreciate it as this is the last package that prevents us from upgrading cc @LKaemmerling @Lloople

**Comment by lahivee** [comment]
@LKaemmerling @Lloople (happy to pay for it)

**Comment by LKaemmerling** [comment]
Hey @j-jalving and @lahivee,

i just pushed v2.3.0 out of the door with support for PHP8. Sorry for the delay, i was on Christmas/new year vacation.

**Comment by lahivee** [comment]
thank you so much!

**Comment by j-jalving** [comment]
Thanks, hope you had a great vacation!
