### ISSUE TITLE
include_external_user_ids must be an array of non empty strings

### ISSUE THREAD

**Issue by MrEduar** [laravel-notification-channels/onesignal#131]
I am repeatedly experiencing this error. It is the response OneSignal gives when making the POST request to send the notification.
```
GuzzleHttp\Exception\ClientException
Client error: `POST https://onesignal.com/api/v1/notifications` resulted in a `400 Bad Request` response:
{"errors":["include_external_user_ids must be an array of non empty strings"]}
```
I guess it is because an empty array is being passed to `include_external_user_ids` in the [line 37 of OneSignalPayloadFactory](https://github.com/laravel-notification-channels/onesignal/blob/master/src/OneSignalPayloadFactory.php#L37) 

However these ids come directly from the `routeNotificationForOneSignal` method in the `User` model. Which is declared as follows

```
    /**
     * Route notifications for the OneSignal channel.
     *
     * @ @param \IlluminateNotifications $notification
     * @return string
     */
    public function routeNotificationForOneSignal($notification)
    {
        return ['include_external_user_ids' => $this->id];
    }
```
The id of my database in the `users` table cannot be null. Therefore I deduce that if this array is being filled with the id of the user.

This is what the payload looks like just before it is sent by the Berkayk\OneSignal package
![image](https://user-images.githubusercontent.com/22550119/115082034-3a664100-9ed3-11eb-8d63-d9c04f5f4c05.png)

I am using 
```
"laravel-notification-channels/onesignal": "^2.1",
"laravel/framework": "^7.0",
```

This error has more than 5k occurrences in the last two days.
You can see a full report [here](https://sentry.blockshift.co/share/issue/c5908107aea04bb08ad02d942ec2f924/).

Any suggestions on how to fix?

**Comment by AlexR1712** [comment]
You need to make sure the  include_external_user_ids property is a string and not a number

**Comment by MrEduar** [comment]
Thank you, this solves the problem. It seems that onesignal has updated the API to better validate this, as previously an array of integers was sufficient to send the notification. PR #132 clarifies the documentation.
