### ISSUE TITLE
include_external_user_ids must be an array of non empty strings

### ISSUE THREAD

**Issue by sheinfeld** [laravel-notification-channels/onesignal#133]
Hey Guys,

Somewhere this past week, something happened with this plugin.

I am unable to send notifications via the user id

```
public function routeNotificationForOneSignal()
    {
        return ['include_external_user_ids' => $this->id];
    }
```

Any ideas?

**Comment by yassine-dabbous** [comment]
Just return an "array of non empty strings"

       `return [ 
              'include_external_user_ids' => [  "{$this->id}"  ]
       ];`

**Comment by sheinfeld** [comment]
Thank you, I was doing something else!

**Comment by tinyCoder32** [comment]
Same here, please fix the documentation at https://laravel-notification-channels.com/onesignal/#usage
