### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by mweghorst** [laravel-notification-channels/onesignal#139]
Please merge this PR so we can use this package with Laravel 9: https://github.com/laravel-notification-channels/onesignal/pull/137

**Comment by tagmood** [comment]
yes, please merge it

**Comment by Jipem** [comment]
@LKaemmerling Please Laravel 9 support 🙏

**Comment by RosiersRobin** [comment]
Bump -> please merge

**Comment by Jipem** [comment]
It's ok, thanks !
https://github.com/laravel-notification-channels/onesignal/releases/tag/v2.4.0
