### ISSUE TITLE
How do you set the users ONE_SIGNAL_PLAYER_ID

### ISSUE THREAD

**Issue by designloud** [laravel-notification-channels/onesignal#14]
Following along the read me file it is not clear how you handle the users subscribing to notifications or how you get/set the ONE_SIGNAL_PLAYER_ID.  Can anyone help me out?

**Comment by IlCallo** [comment]
You must store the devices ID of your users on your database, then return it within the given method name.
Example:

**Comment by DemetAkyol** [comment]
How do I register devices ID database? So what is the code that enables us to get device id?
