### ISSUE TITLE
Additional API parameters

### ISSUE THREAD

**Issue by chancezeus** [laravel-notification-channels/onesignal#16]
I'm wondering if it would be possible (and within the scope of this plugin) to add functionality for setting ios badge information and/or other additional API parameters (content_available, subtitle, attachments) when sending a notification. Maybe through a setParameter/addParameter function (or a __call fluent syntax where ->ios_badgeType sets the badge parameter)...

**Comment by murshid1988** [comment]
Any update on this?

**Comment by aliwesome** [comment]
@chancezeus 
you can send data (key,value) by using `setData` function in `OneSignalMessage` class, here is an example:
```
public function toOneSignal($notifiable)
    {
        return OneSignalMessage::create()
            ->subject($subject)
            ->body($body)
            ->url($url)
            ->setData('show_notification',true);
    }
```

**Comment by chancezeus** [comment]
@aliwesome that only adds "custom" data not api properties like ios_badgeType, I requested the ability to add (custom) api properties (and this also ensures that even when the rest api is updated, this package supports everything, instead of only functionality that is available in the latest release).

**Comment by murshid1988** [comment]
I just used the example provided [here](https://documentation.onesignal.com/v3.0/reference) for PHP as a temporary workaround.

**Comment by tpresing** [comment]
Hi!

How the ttl parameter works?

I set it like this:
`return OneSignalMessage::create()
            ->subject("Test")
            ->body($message)
            ->url($this->url)
            ->setParameter('chrome_web_icon',asset('icon.png'))
            ->setParameter('ttl', 60);`

But i does not care the notification comes after 60 second also.
