### ISSUE TITLE
only able to send by player ids

### ISSUE THREAD

**Issue by yilliot** [laravel-notification-channels/onesignal#17]
need to be able to add "filters" or payload in OneSignalChannel, to before send to Berkayk's 

    sendNotificationCustom($payload);

This package made impossible to send notification by filters.

**Comment by LKDevelopment** [comment]
What specific use case have you? I've added Sending by E-Mail and you can now set additional Parameters (like filters or segments).

**Comment by LKDevelopment** [comment]
Because of lack of activity i close the issue. If you have any other questions or problems, just create a new issue.
