### ISSUE TITLE
Can we make a notification with a link inside the app?

### ISSUE THREAD

**Issue by emilas44** [laravel-notification-channels/onesignal#19]
This is actually not a bug or an issue, it's more like a feature.

I have an app with In-App web browser. and I was just wondering if this is possible? So when a user opens the notification that it opens the app and through the In-App web browser opens the link?

Now the link from notification makes the phone default internet browser to open the link.

**Comment by AshPowell** [comment]
It sounds like your app just needs to support app links and deep linking.

For Android see: https://developer.android.com/training/app-links/deep-linking.html

For iOS see: https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html

You'd make your app handle opening relevant pages in your app for your own urls
