### ISSUE TITLE
action button is not working

### ISSUE THREAD

**Issue by sirius2013** [laravel-notification-channels/onesignal#20]
Hello, I tried to add action button, but that is not working. Thanks
OneSignalMessage::create()
    ->button(
        OneSignalButton::create('id')
            ->text('button text')
            ->icon('button icon')
    );

**Comment by emilas44** [comment]
Did you import the class at the top. Can you check the /storage/logs/laravel.log file

**Comment by sirius2013** [comment]
actually I try this. This will not fire error. but action button is not appearing,
OneSignalMessage::create()
            ->subject($this->titleMessage)
            ->body(str_replace('{ID}', $this->carriageRequest->id, $this->bodyMessage))
            ->button(
                OneSignalButton::create('id')
                ->text('Accept')
            );

**Comment by emilas44** [comment]
Same by me. It also doesn't fire any errors and i am using this code...I want to get an icon and it doesn't work

        ``return OneSignalMessage::create()
                ->subject('Event "' . $this->event->title . '"')
                ->button(
                    OneSignalButton::create()
                        ->text('button text')
                        ->icon('http://www.hultcenter.org/sitecm/i/facebook-icon.png')
                );``

**Comment by emilas44** [comment]
even when i use the default code from the package:

    return OneSignalMessage::create()
        ->subject("Your {$notifiable->service} account was approved!")
        ->body("Click here to see details.")
        ->url('http://onesignal.com')
        ->webButton(
            OneSignalWebButton::create('link-1')
                ->text('Click here')
                ->icon('https://upload.wikimedia.org/wikipedia/commons/4/4f/Laravel_logo.png')
                ->url('http://laravel.com')
     );

It doesn't work. I get this error:


``[2017-05-17 12:46:18] local.ERROR: GuzzleHttp\Exception\ClientException: Client error: `POST https://onesignal.com/api/v1/notifications` resulted in a `400 Bad Request` response:
{"errors":["Message Notifications must have English language content"]}
 in /var/www/html/laravel-projects/4youplatform/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111

**Comment by LKDevelopment** [comment]
@emilas44 @sirius2013 You need to specifiy a messsage. That is a requirment from the one signal API, sorry.
