### ISSUE TITLE
Targeting by Email ?

### ISSUE THREAD

**Issue by olriko** [laravel-notification-channels/onesignal#22]
Hello,

It's possible to target an email (or hash email) instead of "PLAYER_ID" ? 

https://documentation.onesignal.com/docs/web-push-sdk#section--synchashedemail-

**Comment by LKDevelopment** [comment]
@olriko I've implemented it on a fork, can you test and check if this work? currently it works only with one e-mail not with an array (waiting here on a message from OneSignal Support)
https://github.com/LKDevelopment/onesignal/tree/implement-email-targeting

**Comment by Lloople** [comment]
PR merged, it will be available in the new release 🙂
