### ISSUE TITLE
Send notifications to different app_id

### ISSUE THREAD

**Issue by Gaia-Nutrition** [laravel-notification-channels/onesignal#26]
Currently the `app_id` to send notifications to is hardcoded through the settings in `services.php`.

I'm developing a backend serving several apps. Is there a way to provide the `app_id` inside the message?

**Comment by LKDevelopment** [comment]
@Gaia-Nutrition You should be able to overwrite the settings in the service.php on runtime:
https://stackoverflow.com/a/38874160
