### ISSUE TITLE
Can't install in Laravel 5.5.*

### ISSUE THREAD

**Issue by taitrongnguyen107** [laravel-notification-channels/onesignal#27]
![screen shot 2017-09-03 at 12 35 12](https://user-images.githubusercontent.com/14200954/30000851-995ba54c-90a4-11e7-8dfd-c376a1eea870.png)

**Comment by jpmurray** [comment]
See #24 and #25 ...

**Comment by mkwsra** [comment]
I hope they will accept #33 , then it shall resolve #24 & #25

**Comment by freekmurze** [comment]
Fixed
