### ISSUE TITLE
Multiple situation for sending push to user(s), did not consider 

### ISSUE THREAD

**Issue by aliwesome** [laravel-notification-channels/onesignal#29]
I want to send a push once for user and once for user's followers, but this feature was not considered.
thanks for making good packages.

**Comment by aliwesome** [comment]
@mpociot @freekmurze

**Comment by AshPowell** [comment]
Would this not just be a collection of recipients as normal, just combining user and followers?

**Comment by aliwesome** [comment]
@AshPowell 
maybe I could explain this by the code below : 
once user : 
`$user->routeNotificationForOneSignal()`
and once user's follower which is an instance of user : 
`$user->follower->routeNotificationForOneSignal()`

**Comment by LKDevelopment** [comment]
Because of lack of activity i close the issue. If you have any other questions or problems, just create a new issue.

**Comment by aliwesome** [comment]
sweep it under the carpet

**Comment by AshPowell** [comment]
I asked you a question to help diagnose and find a solution but there was no response, that was almost 2 months ago.

I believe what you're trying to accomplish is already possible; if the notification is the same one then combine the collection of users and followers, if it's different then send 2 separate notifications - one to the user and one to the followers, ie:

```
$user = User::where('email', 'email@domain.com')->first();
$followers = $user->followers();

Notification::send($user, new userNotification($data));
Notification::send($followers, new followerNotification($data));
```

Obviously very rough and an example, but shouldn't this cover your needs?
