### ISSUE TITLE
Getting undefined index: app_id

### ISSUE THREAD

**Issue by ednonunes** [laravel-notification-channels/onesignal#30]
Hi! Thanks for the great package.

Well im getting this error when sending pushes: 
![captura de tela 2017-09-26 as 11 48 08](https://user-images.githubusercontent.com/10046732/30866826-aba678bc-a2b0-11e7-81fe-eb769689aa36.png)

My .env is ok with the ONESIGNAL_APP_ID and ONESIGNAL_REST_API_KEY;
MY config/services.php was updated too.
I did $ php artisan config:clear, cache:clear...

`
    public function via($notifiable)
    {
        return [OneSignalChannel::class];
    }

    public function toOneSignal($notifiable)
    {
        return OneSignalMessage::create()
            ->subject("Your account was approved!")
            ->body("Click here to see details.")
            ->url('http://onesignal.com');
    }`

Any ideas?

Thank you!

**Comment by jordankobellarz** [comment]
I made an workaround by changing line 225 of `Berkayk\OneSignal\OneSignalClient` class. 
After: `if (!$parameters['app_id']) {`
Before: `if (!isset($parameters['app_id'])) {`

**Comment by ednonunes** [comment]
@jordankobellarz but its not a good solution working with team :/ 
This is how I solved:

Created a file: App\MyOneSignalMessage.php extending OneSignalMessage, and overriding toArray() method. This way I can inform "app_id" to the payload:


`<?php

namespace App;
use NotificationChannels\OneSignal\OneSignalMessage;

class MyOneSignalMessage extends OneSignalMessage
{
    /**
     * @return array
     */
    public function toArray()
    {
        $message = [
            'contents' => ['en' => $this->body],
            'headings' => ['en' => $this->subject],
            'url' => $this->url,
            'buttons' => $this->buttons,
            'web_buttons' => $this->webButtons,
            'chrome_web_icon' => $this->icon,
            'chrome_icon' => $this->icon,
            'adm_small_icon' => $this->icon,
            'small_icon' => $this->icon,
            'app_id' => env('ONESIGNAL_APP_ID'),
        ];

        foreach ($this->data as $data => $value) {
            Arr::set($message, 'data.'.$data, $value);
        }

        return $message;
    }
}
`

**Comment by AshPowell** [comment]
Same - fixed same way as @ednonunes.

Is this package abandoned? @mpociot @freekmurze

**Comment by nivanmorgan** [comment]
I'm getting the same error after it working on my site for a year. What is the proper fix? Can someone guide me to fix it

**Comment by AshPowell** [comment]
Is this still an issue with the released version? I took out app_id from my custom OneSignalMessage and it seems to still work fine? Only tested local though, not sure if there was any caching involved.

**Comment by Lloople** [comment]
Berkayk fixed this issue in his repository:

https://github.com/berkayk/laravel-onesignal/commit/543f042a845569e26680b7204076240c8f61785a
