### ISSUE TITLE
Using Attachments

### ISSUE THREAD

**Issue by ipshainu** [laravel-notification-channels/onesignal#34]
Hi,

How can i attach images like ios_attachments and big_picture

**Comment by AshPowell** [comment]
I'm assuming you'd use setData($key, $value), including ios_attachments and big_picture

**Comment by LKDevelopment** [comment]
You should be now able to set if with setParameter() in the next released version.

**Comment by AshPowell** [comment]
@LKDevelopment @Lloople is it worth having a custom image/setImage function which would set all the image values... ie:

`'ios_attachments'        => ['id1' => $this->imageUrl],
  'chrome_web_image'  => $this->imageUrl,
  'big_picture'                => $this->imageUrl,
  'adm_big_picture'        => $this->imageUrl,`

I'm aware there is now the new setParameter but I can see image being used frequently and with there being multiple values to set, would it make sense to have its own function?

**Comment by LKDevelopment** [comment]
The Problem with a "One Function sets all Parameter" is, that if you want wo have only an image for chrome or different images for ios/android/chrome you can't set it with this function. So it would be configurabler to use the setParamter function.

**Comment by AshPowell** [comment]
Fair point, would that ever be the case though? Typically you'd want the same values for each platform as the notification is the same... ie subject, body, icon all tend to be the same, I don't see why image wouldnt? 

Worth an ask anyway :)

**Comment by Lloople** [comment]
Well, we can have a method called `setImages` for example which do the job to add all of them, and if you want different images then use the `setParameter` 🤔

**Comment by AshPowell** [comment]
Excellent! It just makes it a little easier for something that will be a common function. (And now master has all the extra functionality my local extended version did, all is good :) )
