### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/onesignal#38]
Both @mpociot and myself don't have time to maintain this package anymore. We are looking for a maintainer for this package. 

Ideally it's someone who already uses this package on multiple projects and has a good understanding of Laravel and knows (or whats to learn) package development.

Who's up for this?

**Comment by Lloople** [comment]
Hi Freek,

I would like to help with this 🙂

**Comment by hemratna** [comment]
Hi Lloople

I would love to join you.

**Comment by LKDevelopment** [comment]
Hey @freekmurze and @mpociot,

i use this package in multiple projects - private projects and business projects - and have big experience with laravel and contributed a little bit to your spatie packages. I would love to join you, and learn from you, even if you doesn't have the time to maintain this project anymore.

**Comment by freekmurze** [comment]
Based on GitHub profile and personal interactions in the past I've added @Lloople and @LKDevelopment as admins of this repo. 

Please do talk a bit with each other on how you see this package evolving and improve the package as you see fit. 

@hemratna I've not added you as admin, but thank you very much for the offer. Of course you can still send issues and PRs to help the maintainers of this package.
