### ISSUE TITLE
Min Php Version

### ISSUE THREAD

**Issue by ecomunicarte** [laravel-notification-channels/onesignal#57]
The title of the package is "...for Laravel 5.3+", but the min PHP version is 7.0 since the package's version 1.1.0. I have seen that in changelog after hours looking for why it does not work. 

Laravel 5.3, and 5.4 don't require PHP 7, so I think you could indicate that requirement in the readme.

**Comment by LKDevelopment** [comment]
As of Version 1.1.0 the min PHP Version is 7.0.0, the Changelog says these:
https://github.com/laravel-notification-channels/onesignal/blob/master/CHANGELOG.md

If you want to use it in PHP Version < 7.0.0 the latest working version is 1.0.2.

**Comment by ecomunicarte** [comment]
Ok, so I think it must be indicated in readme since the requirements are different from laravel ones.
