### ISSUE TITLE
[Composer\Downloader\TransportException]

### ISSUE THREAD

**Issue by jorgelopezowd** [laravel-notification-channels/onesignal#61]
Error trying to install 

 The "http://packagist.org/p/symfony/polyfill-php70%244546075da4e1484628161afae5f1d4c964c7923d6ca8748a34cce8503299f80f.json" file could not be downloaded (HTTP/1.1 404 Not Found)

Laravel 5.5
composer data
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "mpociot/laravel-apidoc-generator": "^2.0"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "~1.0",
        "phpunit/phpunit": "~6.0",
        "symfony/thanks": "^1.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

**Comment by LKDevelopment** [comment]
That is something for the composer repo, not for us. Looks like there was an issue on packagist or something else.
