### ISSUE TITLE
Connections remain after doing job

### ISSUE THREAD

**Issue by mahdyfo** [laravel-notification-channels/onesignal#62]
After sending some notifications, the connections will remain on **CLOSE_WAIT** state. The count of connections is equal to count of queue workers. It makes the server slow and sometimes it consumes a lot of bandwidth and make the whole application slow. 
netstat -n -p :
```Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name

tcp       32      0 88.99.00.00:42268      104.16.204.165:443      CLOSE_WAIT  12828/php

tcp       32      0 88.99.00.00:50298      104.16.205.165:443      CLOSE_WAIT  12832/php

tcp       32      0 88.99.00.00:44554      104.16.204.165:443      CLOSE_WAIT  12824/php
```

These ( ips: 104.16.20*.165 ) are for onesignal servers. Sometimes **I should block all of them from iptables and kill -9 all php processes to restore the server speed**.

Maybe it's because of not closing the request? Because Laravel doesn't destroy the queue scripts and they should flush manually. Please help to get out of this.

**Comment by LKDevelopment** [comment]
This is a really strange behavior, but actually not in our package scope. Since under the hood the Client we use, use GuzzleHttp. After a little bit research on google it looks like this is normal. I will look on some of my projects with queue workers (but without this package) if the behavior is the same.

**Comment by LKDevelopment** [comment]
Since this isn't in our direct scope i will label it actually with "bug" and "wont fix", but i'll keep looking at it.

**Comment by mahdyfo** [comment]
Looks like it is fixed by adding CURLOPT_FORBID_REUSE = true

**Comment by LKDevelopment** [comment]
Since we doesn't call the curl requests directly, this issue should be added to the onesignal client we use: https://github.com/berkayk/laravel-onesignal
