### ISSUE TITLE
Subdomain

### ISSUE THREAD

**Issue by ahmedalmulki** [laravel-notification-channels/onesignal#69]
how can I use this library with multiple subdomains , because as I understand OneSignal not supporting multiple subdomains with same origin ?

**Comment by LKDevelopment** [comment]
Can you please describe your use case a little bit more? Doesn't get what you want to do.

**Comment by ahmedalmulki** [comment]
I have domain with 7 subdomains , I want to prevent users getting re-prompted when they access to 2.example.com if they already Allow notification from 1.example.com or any other subdomain or from main domain .

**Comment by AshPowell** [comment]
Maybe this will help... https://documentation.onesignal.com/docs/web-push-complex-integrations

but really, if the content is so different they require the sites to be on multiple sub-domains, then the user isn't really subscribing to all of them, I think above anything this could just lead to a bad user experience.

**Comment by ahmedalmulki** [comment]
@AshPowell I already read this article , and the content of my subdomains almost same and they have same root document I am just get some different posts depend on subdomain as client need ,
but my question is regarding mentioned docs can I rely on cookies what if the visitor remove cookies from his browser ?

**Comment by AshPowell** [comment]
@ahmedalmulki I would just treat users who remove cookies as a new user and reprompt... It'll be rare that a user removes cookies.

If they can login via your website you could always store their subscription status and check it before prompting?

**Comment by ahmedalmulki** [comment]
@AshPowell yes you are right , but if I re-prompt visitor after delete cookies, later on I will have many unuseful subscriber right , is there any way to remove these subscriber ?
unfortunately visitor can't login via this website .

**Comment by AshPowell** [comment]
@ahmedalmulki I'm not sure of any other way - seems more like a OneSignal issue rather than the Laravel OneSignal channel package - I'd try contacting OneSignal directly and see if they have any suggestions :)

**Comment by ahmedalmulki** [comment]
@AshPowell Thanks for your support 👍

**Comment by ahmedalmulki** [comment]
Hi @AshPowell I install OneSignal in my website , and use cookies to know if the visitor subscribe or no and everything is ok now , but I get this error from OneSignal and I don't know how can I fix :( ,
`OneSignalError.js:18 Uncaught (in promise) Error: OneSignal: This web push config can only be used on https://www.example.net. Your current origin is https://istanbul.example.net.`

**Comment by LKDevelopment** [comment]
Please ask this to the onesignal Support, since we doesnt give Support For Problems Outside of the package scope.
