### ISSUE TITLE
Send a notification to all users

### ISSUE THREAD

**Issue by misog** [laravel-notification-channels/onesignal#78]
Hi, is it possible to send a notification to all users in OneSignal? Without specifying player IDs in routeNotificationForOneSignal.
Thanks

**Comment by LKaemmerling** [comment]
Hey, 

sorry for the late reply. This is currently not possible.

**Comment by r94ever** [comment]
@misog If you are using Laravel 5.6 or above, you can pass a param, which is instance of your notification class, for `routeNotificationForOneSignal()` method, like this: `routeNotificationForOneSignal($notification)`
