### ISSUE TITLE
How to send groupKey and largeIcon?

### ISSUE THREAD

**Issue by Mr-Anonymous** [laravel-notification-channels/onesignal#81]
At the moment, I am sending the push notification messages from my Laravel 5.3 backend to OneSignal like this:

```
public function toOneSignal($notifiable)
    {
        return OneSignalMessage::create()
                               ->subject($this->subjectMsg)
                               ->body($this->notificationBody)
                               ->url($this->actionUrl);
    }
```

How can I also send a `groupKey` and `largeIcon`?

Thanks for your help.

**Comment by Lloople** [comment]
Hi @Mr-Anonymous,

Sorry for the late reply. Being pretty busy lately.

In case you haven't figured it out yet, take a look at [at the method setParameter of the Message class](https://github.com/laravel-notification-channels/onesignal/blob/master/src/OneSignalMessage.php#L108), I think it's what you needed.
