### ISSUE TITLE
How to register device on onesignal ?

### ISSUE THREAD

**Issue by afrazahmmad** [laravel-notification-channels/onesignal#82]
Hello dear !
Is there a way to register device on one-signal because one-signal only sends notification to those devices which are registered.  
One signal api provides [endpoint ](https://documentation.onesignal.com/reference#edit-device)to do this but this package does not contain any info about it.
May be this package is only focused on web not mobile devices.

**Comment by LKaemmerling** [comment]
Since we are a notification channel, we don't support things like adding a device to OneSignal, this should do your app.
