### ISSUE TITLE
Chrome Big Picture not work

### ISSUE THREAD

**Issue by r94ever** [laravel-notification-channels/onesignal#93]
Hi,

I need to set an large image as attachment for my notifications, but it doesn't work. This is my sample code:

```
public function toOneSignal($notifiable)
{
    return OneSignalMessage::create()
        ->setIcon($this->site_logo)
        ->setImageAttachments($this->post->featured_image)
        ->setSubject($this->post->title)
        ->setBody($this->post->getExcerpt(120))
        ->setUrl($this->post->canonical_link)
        ->setButton(
            OneSignalButton::create('id') ->text('Download')
        );
}
```

Please help me solve this. Any help would be appreciated! Thanks

**Comment by Lloople** [comment]
What's the content of the image property?

```
$this->post->featured_image
```

You should point to the absolute url if I recall correctly, like

```
...
->setImageAttachments(url('images/posts/'.$this->post->featured_image))
...
```

**Comment by r94ever** [comment]
> What's the content of the image property?
> 
> ```
> $this->post->featured_image
> ```
> 
> You should point to the absolute url if I recall correctly, like
> 
> ```
> ...
> ->setImageAttachments(url('images/posts/'.$this->post->featured_image))
> ...
> ```

Hi,

The value of $this->post->featured_image is FULL URL of image, like this: `https://mydomain.com/storages/2019/05/my-post-title.jpg`

**Comment by LKaemmerling** [comment]
Do you test it on MacOS? As of Chrome 59 this isn‘t available anymore: https://onesignal.com/blog/web-push-changes-in-chrome-59/

**Comment by r94ever** [comment]
@LKaemmerling , I test in Windows 10, Chrome 74

**Comment by LKaemmerling** [comment]
Have you tried the tips from https://documentation.onesignal.com/docs/notification-images-not-showing? I can not find an error in the implementation.  Did you notice that the file need to be a local image?  See https://documentation.onesignal.com/reference#section-attachments for more details

**Comment by r94ever** [comment]
@LKaemmerling Same with you, I can not find any mistake of this package also. And as I understand, the local image url is the full URL of image which is stored in the domain registered with Onesignal. And if it is true, my parameter is not wrong...

**Comment by LKaemmerling** [comment]
Then i am sorry, but i guess only the Onesignal support can help you.

**Comment by r94ever** [comment]
@LKaemmerling thank you so much! I will ask the Onesignal team 😎

**Comment by atymic** [comment]
Did you get this solved?

**Comment by r94ever** [comment]
Unfortunately no and I am still using without Chrome big pictures :(

**Comment by r94ever** [comment]
@atymic it will be solved in next release. I've tested and it worked fine :)

**Comment by atymic** [comment]
Perfect :)
