### ISSUE TITLE
Sending notification to tags(notification no show)

### ISSUE THREAD

**Issue by pateljatin125** [laravel-notification-channels/onesignal#94]
My notification class like this:
Laravel 5.8  : App\User model class 

1:  I have set the  app_id,rest_api_key in config/services.php file

2:I have passed value like this.(User model)
        public function routeNotificationForOneSignal() {
        return ['tags' => ['field' => 'user_id', 'relation' => '=', 'value' => 5]];
    }

3: My notification class like this:(App\Notifications\InvoicePaid class)

use NotificationChannels\OneSignal\OneSignalChannel;
use NotificationChannels\OneSignal\OneSignalMessage;
use NotificationChannels\OneSignal\OneSignalWebButton;
use Illuminate\Notifications\Notification;

    public function via($notifiable)
    {   
        return [OneSignalChannel::class];
    }     

public function toOneSignal($notifiable)
    {
       return OneSignalMessage::create()
         ->subject("Your Notifications")
         ->body("Click here to Notifications.");
         ->url('http://127.0.0.1:8000/home')
        ->webButton(
            OneSignalWebButton::create('http://127.0.0.1:8000/home')
                ->text('button text')
                ->icon('button icon')
                ->url('http://127.0.0.1:8000/home')
        ); 
     
I have not found any error but still Push notification not show . Please help me.

**Comment by LKaemmerling** [comment]
I guess the index should be `tag` and not `tags`.

**Comment by atymic** [comment]
@pateljatin125 did you get this solved?

**Comment by LKaemmerling** [comment]
Closed because of lack of activity. If you still have this issue, feel free to reopen it.
