### ISSUE TITLE
Notification Send without errors, but in onesignal dashboard nothing

### ISSUE THREAD

**Issue by Fitzaa** [laravel-notification-channels/onesignal#95]
public function toOneSignal($notifiable)
    {
        return OneSignalMessage::create()
                               ->subject($this->pushNotification()->subject)
                               ->body($this->pushNotification()->body)
                               ->setData('notification_id', $this->id);
    }

**Comment by Fitzaa** [comment]
public function via(User $notifiable)
    {
        $via   = ['database'];
        $via[] = OneSignalChannel::class;

        return $via;
    }

in user.php

public function routeNotificationForOneSignal()
    {
return $this->getDevicesArray();
    }

**Comment by LKaemmerling** [comment]
Please contact the OneSignal Support in this case.

**Comment by Fitzaa** [comment]
the problem resolved itself, notifications began to come, thanks
